# Generated by Django 2.2 on 2019-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='detail1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='test',
            name='detail2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
